### ISSUE TITLE
Error gas ? Abi ?

### ISSUE THREAD

**Issue by SecousseClama** [goosedefi/goose-frontend-farms#1]
Hello, 
I deploy this frontend, put my config contract and ABI masterchef,
he return that : 

Uncaught (in promise) Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.

Can you help me ? 
And sorry for my bad english. 
Thank guys

**Comment by erdemozturk52** [comment]
I am getting the same error. What's the solution?

**Comment by htskltd91989** [comment]
did either of you figure this out?

> I am getting the same error. What's the solution?



> Hello,
> I deploy this frontend, put my config contract and ABI masterchef,
> he return that :
> 
> Uncaught (in promise) Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
> 
> Can you help me ?
> And sorry for my bad english.
> Thank guys

**Comment by wanglonghong** [comment]
Hi, guys.

"Uncaught (in promise) Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced."

This is not issue of this repository. Have you published all the contracts and added pools to MasterChef contract?
It uses multicall contracts to get result at once from several contracts. So if there are some conracts not published or not added, it will fail. In this case, you will meet such issue. 

Thanks.

**Comment by wanglonghong** [comment]
> Hello,
> I deploy this frontend, put my config contract and ABI masterchef,
> he return that :
> 
> Uncaught (in promise) Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
> 
> Can you help me ?
> And sorry for my bad english.
> Thank guys

**Comment by kdeasymoneysniper** [comment]
Hello, I am facing the same issue, did anybody manage to solve it?
